module.exports = {
  apps: [
    {
      name: "opencode-server",
      script: "bun",
      args: "run --cwd packages/opencode --conditions=browser src/index.ts serve --hostname 0.0.0.0 --port 3400 --cors http://macmini:3001",
      cwd: "/Users/tallpizza/project/opencode",
      interpreter: "none",
      env: {
        NEO4J_URI: "bolt://macmini:7788",
        NEO4J_USER: "neo4j",
        NEO4J_PASSWORD: "password1234",
        ONTOLOGY_SPACES_DB: "/Users/tallpizza/project/ontology/.pi/spaces.db",
        // Project-level isolation
        XDG_CONFIG_HOME: "/Users/tallpizza/project/opencode/.local/config",
        XDG_DATA_HOME: "/Users/tallpizza/project/opencode/.local/share",
        XDG_CACHE_HOME: "/Users/tallpizza/project/opencode/.local/cache",
        XDG_STATE_HOME: "/Users/tallpizza/project/opencode/.local/state",
        OPENCODE_DISABLE_EXTERNAL_SKILLS: "1",
        OPENCODE_DISABLE_CLAUDE_CODE_PROMPT: "1",
        OPENCODE_ENABLE_EXA: "1",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      out_file: "./logs/server-out.log",
      error_file: "./logs/server-error.log",
      merge_logs: true,
      max_memory_restart: "1G",
      autorestart: true,
      min_uptime: "10s",
      max_restarts: 10,
    },
    {
      name: "opencode-app",
      script: "bun",
      args: "--cwd packages/app dev -- --host 0.0.0.0 --port 3001",
      cwd: "/Users/tallpizza/project/opencode",
      interpreter: "none",
      env: {
        VITE_OPENCODE_SERVER_HOST: "macmini",
        VITE_OPENCODE_SERVER_PORT: "3400",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      out_file: "./logs/app-out.log",
      error_file: "./logs/app-error.log",
      merge_logs: true,
      max_memory_restart: "1G",
      autorestart: true,
      min_uptime: "10s",
      max_restarts: 10,
    },
  ],
}
